### PR TITLE
Handle double clicks on Display Panel when shift- or tilt-clicking.

### PR DESCRIPTION
**Pull request by Brow71189**

### CODE REVIEW

**Comment by Brow71189** [comment]
This change requires nion-software/nionswift#415.

**Comment by cmeyer** [comment]
What does this do? It looks like a no-op.

**Comment by Brow71189** [comment]
Yes that's exactly the point: You don't want the double click to be handled
as a double click when you are using click-to-shift or -to-tilt. This,
together with the nionswift change, is the fix for part of Niklas' email
yesterday about click-to-tilt issues.

Chris Meyer <notifications@github.com> schrieb am Do., 14. Mai 2020, 17:25:

**Comment by cmeyer** [comment]
Ok, give me a day or so to think through this. A general replacement mechanism for adding new tools is what I'll propose (if anything). Otherwise I'll merge this after a few days until a better solution is in place.

**Comment by Brow71189** [comment]
> 
> 
> Ok, give me a day or so to think through this. A general replacement mechanism for adding new tools is what I'll propose (if anything). Otherwise I'll merge this after a few days until a better solution is in place.

**Comment by Brow71189** [comment]
Did you have a change to think this through yet?

**Comment by cmeyer** [comment]
I almost certainly don't want to add this. But I don't want to close it just yet.

As reference, the replacement might be https://github.com/nion-software/nionswift/issues/338

But additional avenues might be:
1. do nothing. it's been this way for a few years and I'm not convinced we've thought through click-to-shift well.
2. do not make double click reset zoom. i'm not sure why this was added in the first place. do any other applications handle double click that way? it's almost certain that this will cause other similar problems in the future; so excluding for this one particular case doesn't solve the bigger picture.
3. rethink click-to-shift. should we reconsider dragging to shift? (the answer to this should move offline)

**Comment by Brow71189** [comment]
1. I strongly disagree: This is exactly one of the many small annoying things that we discussed recently and that we agreed on trying to get rid of over time. So doing nothing is really exactly the opposite of what we want and just bad practice in my opinion.

2. That would be an option. Personally I'm also not a fan of having double click reset zoom. Maybe it was added to be consistent with line plots? This might also make some users unhappy if they are used to the double-click reset feature.

3. I'm not sure drag-to-shift would work very well. In imagination this would feel like adjusting the window layout via a VNC connection with a lag of 1 s because the stage reacts with a delay to user input simply because it is a mechanical system with a fixed reaction time.

**Comment by cmeyer** [comment]
I went with option 2. Please file a new issue if it still has a problem.

https://github.com/nion-software/nionswift/commit/b9c0033b3cabcc0762e33263293a9cf8035cd79f

**Pull request closed without merging**
