### PR TITLE
Update 'uncropped_xdata' in each iteration.

### PR DESCRIPTION
**Pull request by Brow71189**
It looks like the Nion cameras always send the same object as "uncropped_xdata" for each call to "acquire_synchronized_continue". However, I don't think this is something that can be guaranteed for all cameras, so "uncropped_xdata" should be read from "partial_data_info" in each iteration.

### CODE REVIEW

**Comment by cmeyer** [comment]
I'm looking at this now (I wish I had made more comments about the code originally!). What problem is this trying to solve? How does the problem arise?

**Comment by Brow71189** [comment]
The problem is that with a camera that does not re-use the same object for "partial_data_info.xdata" on every call of "acquire_synchronized_continue" the system tries to write the same chunk of data (which it got initially from partial_data_info.xdata) over and over again.

**Comment by cmeyer** [comment]
Merged 0868523144f35ab76bf21be68c513cbe4738919e

**Comment by cmeyer** [comment]
@Brow71189 I know already merged this, but I think I'm going to un-merge this.

See https://github.com/nion-software/nion-instrumentation/issues/192

**Comment by cmeyer** [comment]
... sorry I forgot how we resolved this one. Is this still something that is needed?

**Comment by Brow71189** [comment]
You re-opened the pull request but did not actually unmerge this. If possible I'd like that change to stay in there because I'm still convinced that it is logically correct way.

**Comment by cmeyer** [comment]
Ok I'll leave it until I have a better reason to remove it. :) 
Closing this.

**Pull request closed without merging**
